"use client"
import * as React from 'react';
import { useState, useEffect } from "react"
import Box from '@mui/material/Box';
import Container from '@mui/material/Container';
import Grid from '@mui/material/Unstable_Grid2';
import axios from 'axios';
import Drawer from '@mui/material/Drawer';
import Typography from '@mui/material/Typography';
import List from '@mui/material/List';
import ListItem from '@mui/material/ListItem';
import Alert from '@mui/material/Alert';
import AlertTitle from '@mui/material/AlertTitle';
import MediaCard from '@/components/MediaCard';
import { DataGrid, GridColDef, GridValueGetterParams } from '@mui/x-data-grid';


const columns: GridColDef[] = [
  { field: 'id', headerName: 'ID', width: 90 },
  {field:'ACQAMT', headerName: 'ACQAMT', width: 90 },
  {field:'ACQYMD_SEQ',headerName: 'ACQYMD_SEQ',width: 150,editable: true,},
  {field:'AFT_FY_ACQAMT',headerName: 'AFT_FY_ACQAMT',width: 150,editable: true,},
  {field:'AFT_FY_BOOKESTAMT',headerName: 'AFT_FY_BOOKESTAMT',type: 'number',width: 110,editable: true,},
  {field:'AFT_FY_DIS_PASSINT',headerName: 'AFT_FY_DIS_PASSINT',description: 'This column has a value getter and is not sortable.',sortable: false,width: 160,valueGetter: (params: GridValueGetterParams) =>`${params.row.firstName || ''} ${params.row.lastName || ''}`,},
  {field:'AFT_FY_GEN_PASSINT',headerName: 'AFT_FY_GEN_PASSINT',width: 150,editable: true,},
  {field:'AFT_FY_IACQAMT',headerName: 'AFT_FY_IACQAMT',width: 150,editable: true,},
  {field:'AFT_FY_IBOOKESTAMT',headerName: 'AFT_FY_IBOOKESTAMT',width: 150,editable: true,},
  {field:'AFT_FY_PRM_PASSINT',headerName: 'AFT_FY_PRM_PASSINT',width: 150,editable: true,},
  {field:'AFT_FY_REM_PREGETINT',headerName: 'AFT_FY_REM_PREGETINT',width: 150,editable: true,},
  {field:'AFT_FY_SAV_DIS_NOGETINT',headerName: 'AFT_FY_SAV_DIS_NOGETINT',width: 150,editable: true,},
  {field:'AFT_FY_SAV_ESTPL',headerName: 'AFT_FY_SAV_ESTPL',width: 150,editable: true,},
  {field:'AFT_FY_SAV_ETC_CVTPL',headerName: 'AFT_FY_SAV_ETC_CVTPL',width: 150,editable: true,},
  {field:'AFT_FY_SAV_GEN_CVTPL',headerName: 'AFT_FY_SAV_GEN_CVTPL',width: 150,editable: true,},
  {field:'AFT_FY_SAV_GEN_NOGETINT',headerName: 'AFT_FY_SAV_GEN_NOGETINT',width: 150,editable: true,},
  {field:'AFT_FY_SAV_IESTPL',headerName: 'AFT_FY_SAV_IESTPL',width: 150,editable: true,},
  {field:'AFT_FY_SAV_PRM_NOGETINT',headerName: 'AFT_FY_SAV_PRM_NOGETINT',width: 150,editable: true,},
  {field:'APP_CLSPRICE_YMD',headerName: 'APP_CLSPRICE_YMD',width: 150,editable: true,},
  {field:'APP_CURR_CD',headerName: 'APP_CURR_CD',width: 150,editable: true,},
  {field:'APP_RATE',headerName: 'APP_RATE',width: 150,editable: true,},
  {field:'BEF_ACQAMT',headerName: 'BEF_ACQAMT',width: 150,editable: true,},
  {field:'BEF_CLSPRICE',headerName: 'BEF_CLSPRICE',width: 150,editable: true,},
  {field:'BEF_FY_DIS_NOGETINT_CVTPL',headerName: 'BEF_FY_DIS_NOGETINT_CVTPL',width: 150,editable: true,},
  {field:'BEF_FY_DIS_PASSINT_CVTPL',headerName: 'BEF_FY_DIS_PASSINT_CVTPL',width: 150,editable: true,},
  {field:'BEF_FY_GEN_CVTPL',headerName: 'BEF_FY_GEN_CVTPL',width: 150,editable: true,},
  {field:'BEF_FY_GEN_NOGETINT_CVTPL',headerName: 'BEF_FY_GEN_NOGETINT_CVTPL',width: 150,editable: true,},
  {field:'BEF_FY_GEN_PASSINT_CVTPL',headerName: 'BEF_FY_GEN_PASSINT_CVTPL',width: 150,editable: true,},
  {field:'BEF_FY_PRM_NOGETINT_CVTPL',headerName: 'BEF_FY_PRM_NOGETINT_CVTPL',width: 150,editable: true,},
  {field:'BEF_FY_PRM_PASSINT_CVTPL',headerName: 'BEF_FY_PRM_PASSINT_CVTPL',width: 150,editable: true,},
  {field:'BEF_FY_SAV_CVTPL_BS	',headerName:'BEF_FY_SAV_CVTPL_BS',width: 150,editable: true,}, 
  {field:'BEF_FY_SAV_ESTPL',headerName:'BEF_FY_SAV_ESTPL',width: 150,editable: true,},
  {field:'BEF_FY_SAV_ESTPL_BS',headerName:'BEF_FY_SAV_ESTPL_BS',width: 150,editable: true,},
  {field:'BEF_FY_SAV_IESTPL',headerName:'BEF_FY_SAV_IESTPL',width: 150,editable: true,},
  {field:'BEF_FY_SAV_IESTPL_BS',headerName:'BEF_FY_SAV_IESTPL_BS',width: 150,editable: true,},
  {field:'BEF_FY_SAV_IREDEMPL',headerName:'BEF_FY_SAV_IREDEMPL',width: 150,editable: true,},
  {field:'BEF_FY_SAV_REDEMPL',headerName:'BEF_FY_SAV_REDEMPL',width: 150,editable: true,},
  {field:'BEF_IACQAMT',headerName:'BEF_IACQAMT',width: 150,editable: true,},
  {field:'BEF_PARAMT',headerName:'BEF_PARAMT',width: 150,editable: true,},
  {field:'BN_POSITION',headerName:'BN_POSITION',width: 150,editable: true,},
  {field:'BOOKESTAMT',headerName:'BOOKESTAMT',width: 150,editable: true,},
  {field:'BUYRATE',headerName:'BUYRATE',width: 150,editable: true,},
  {field:'BUY_CPI_PARAMT',headerName:'BUY_CPI_PARAMT',width: 150,editable: true,},
  {field:'CHGDURA',headerName:'CHGDURA',width: 150,editable: true,},
  {field:'CLSPRICE',headerName:'CLSPRICE',width: 150,editable: true,},
  {field:'CLS_EXRATE',headerName:'CLS_EXRATE',width: 150,editable: true,},
  {field:'CONVEX',headerName:'CONVEX',width: 150,editable: true,},
  {field:'CPI',headerName:'CPI',width: 150,editable: true,},
  {field:'CPI_PARAMT',headerName:'CPI_PARAMT',width: 150,editable: true,},
  {field:'CURR_CD',headerName:'CURR_CD',width: 150,editable: true,},
  {field:'DEC_ACQAMT',headerName:'DEC_ACQAMT',width: 150,editable: true,},
  {field:'DEC_IACQAMT',headerName:'DEC_IACQAMT',width: 150,editable: true,},
  {field:'DEC_PARAMT',headerName:'DEC_PARAMT',width: 150,editable: true,},
  {field:'DIS_NOGETINT',headerName:'DIS_NOGETINT',width: 150,editable: true,},
  {field:'DIS_NOGETTAX',headerName:'DIS_NOGETTAX',width: 150,editable: true,},
  {field:'DIS_NOPAYTAX',headerName:'DIS_NOPAYTAX',width: 150,editable: true,},
  {field:'DIS_NOPAY_RSDTAX',headerName:'DIS_NOPAY_RSDTAX',width: 150,editable: true,},
  {field:'DIS_PASSINT',headerName:'DIS_PASSINT',width: 150,editable: true,},
  {field:'DIS_PASSTAX'	,headerName:'DIS_PASSTAX',width: 150,editable: true,},
  {field:'DIS_PASS_RSDTAX',headerName:'DIS_PASS_RSDTAX',width: 150,editable: true,},
  {field:'DIS_PREPAYTAX',headerName:'DIS_PREPAYTAX',width: 150,editable: true,},
  {field:'DIS_PREPAY_RSDTAX',headerName:'DIS_PREPAY_RSDTAX',width: 150,editable: true,},
  {field:'DIS_SALE_PREGETINT',headerName:'DIS_SALE_PREGETINT',width: 150,editable: true,},
  {field:'DURA',headerName:'DURA',width: 150,editable: true,},
  {field:'EFFECT_INTRATE',headerName:'EFFECT_INTRATE',width: 150,editable: true,},
  {field:'ESTAMT',headerName:'ESTAMT',width: 150,editable: true,},
  {field:'ESTAMT_UNIT',headerName:'ESTAMT_UNIT',width: 150,editable: true,},
  {field:'ESTPL',headerName:'ESTPL',width: 150,editable: true,},
  {field:'EST_FIRM_GRADE',headerName:'EST_FIRM_GRADE',width: 150,editable: true,},
  {field:'ETC_CVTPL',headerName:'ETC_CVTPL',width: 150,editable: true,},
  {field:'FST_ACQAMT',headerName:'FST_ACQAMT',width: 150,editable: true,},
  {field:'FST_IACQAMT',headerName:'FST_IACQAMT',width: 150,editable: true,},
  {field:'FST_TRADE_YMD',headerName:'FST_TRADE_YMD',width: 150,editable: true,},
  {field:'FUND',headerName:'FUND',width: 150,editable: true,},
  {field:'GC_AC',headerName:'GC_AC',width: 150,editable: true,},
  {field:'GEN_CVTPL',headerName:'GEN_CVTPL',width: 150,editable: true,},
  {field:'GEN_NOGETINT',headerName:'GEN_NOGETINT',width: 150,editable: true,},
  {field:'GEN_NOGETTAX',headerName:'GEN_NOGETTAX',width: 150,editable: true,},
  {field:'GEN_NOPAYTAX',headerName:'GEN_NOPAYTAX',width: 150,editable: true,},
  {field:'GEN_NOPAY_RSDTAX',headerName:'GEN_NOPAY_RSDTAX',width: 150,editable: true,},
  {field:'GEN_PASSINT',headerName:'GEN_PASSINT',width: 150,editable: true,},
  {field:'GEN_PASSTAX',headerName:'GEN_PASSTAX',width: 150,editable: true,},
  {field:'GEN_PASS_RSDTAX',headerName:'GEN_PASS_RSDTAX',width: 150,editable: true,},
  {field:'GEN_PREPAYTAX',headerName:'GEN_PREPAYTAX',width: 150,editable: true,},
  {field:'GEN_PREPAY_RSDTAX',headerName:'GEN_PREPAY_RSDTAX',width: 150,editable: true,},
  {field:'GEN_SALE_PREGETINT',headerName:'GEN_SALE_PREGETINT',width: 150,editable: true,},
  {field:'GET_DIS_NOGETINT',headerName:'GET_DIS_NOGETINT',width: 150,editable: true,},
  {field:'GET_DIS_NOGETTAX',headerName:'GET_DIS_NOGETTAX',width: 150,editable: true,},
  {field:'GET_DIS_PASSINT',headerName:'GET_DIS_PASSINT',width: 150,editable: true,},
  {field:'GET_GEN_NOGETINT',headerName:'GET_GEN_NOGETINT',width: 150,editable: true,},
  {field:'GET_GEN_NOGETTAX',headerName:'GET_GEN_NOGETTAX',width: 150,editable: true,},
  {field:'GET_GEN_PASSINT',headerName:'GET_GEN_PASSINT',width: 150,editable: true,},
  {field:'GET_IDIS_NOGETINT',headerName:'GET_IDIS_NOGETINT',width: 150,editable: true,},
  {field:'GET_IDIS_NOGETTAX',headerName:'GET_IDIS_NOGETTAX',width: 150,editable: true,},
  {field:'GET_IDIS_PASSINT',headerName:'GET_IDIS_PASSINT',width: 150,editable: true,},
  {field:'GET_IGEN_NOGETINT',headerName:'GET_IGEN_NOGETINT',width: 150,editable: true,},
  {field:'GET_IGEN_NOGETTAX',headerName:'GET_IGEN_NOGETTAX',width: 150,editable: true,},
  {field:'GET_IGEN_PASSINT',headerName:'GET_IGEN_PASSINT',width: 150,editable: true,},
  {field:'GET_IPRM_NOGETINT',headerName:'GET_IPRM_NOGETINT',width: 150,editable: true,},
  {field:'GET_IPRM_NOGETTAX',headerName:'GET_IPRM_NOGETTAX',width: 150,editable: true,},
  {field:'GET_IPRM_PASSINT',headerName:'GET_IPRM_PASSINT',width: 150,editable: true,},
  {field:'GET_PRM_NOGETINT',headerName:'GET_PRM_NOGETINT',width: 150,editable: true,},
  {field:'GET_PRM_NOGETTAX',headerName:'GET_PRM_NOGETTAX',width: 150,editable: true,},
  {field:'GET_PRM_PASSINT',headerName:'GET_PRM_PASSINT',width: 150,editable: true,},
  {field:'HOL_DUE_IPASSINT',headerName:'HOL_DUE_IPASSINT',width: 150,editable: true,},
  {field:'HOL_DUE_PASSINT',headerName:'HOL_DUE_PASSINT',width: 150,editable: true,},
  {field:'IACQAMT',headerName:'IACQAMT',width: 150,editable: true,},
  {field:'IBOOKESTAMT',headerName:'IBOOKESTAMT',width: 150,editable: true,},
  {field:'IDIS_NOGETINT',headerName:'IDIS_NOGETINT',width: 150,editable: true,},
  {field:'IDIS_NOGETTAX',headerName:'IDIS_NOGETTAX',width: 150,editable: true,},
  {field:'IDIS_NOPAYTAX',headerName:'IDIS_NOPAYTAX',width: 150,editable: true,},
  {field:'IDIS_NOPAY_RSDTAX',headerName:'IDIS_NOPAY_RSDTAX',width: 150,editable: true,},
  {field:'IDIS_PASSINT',headerName:'IDIS_PASSINT',width: 150,editable: true,},
  {field:'IDIS_PASSTAX',headerName:'IDIS_PASSTAX',width: 150,editable: true,},
  {field:'IDIS_PASS_RSDTAX',headerName:'IDIS_PASS_RSDTAX',width: 150,editable: true,},
  {field:'IDIS_PREPAYTAX',headerName:'IDIS_PREPAYTAX',width: 150,editable: true,},
  {field:'IDIS_PREPAY_RSDTAX',headerName:'IDIS_PREPAY_RSDTAX',width: 150,editable: true,},
  {field:'IDIS_SALE_PREGETINT',headerName:'IDIS_SALE_PREGETINT',width: 150,editable: true,},
  {field:'IESTAMT',headerName:'IESTAMT',width: 150,editable: true,},
  {field:'IESTAMT_UNIT',headerName:'IESTAMT_UNIT',width: 150,editable: true,},
  {field:'IESTPL',headerName:'IESTPL',width: 150,editable: true,},
  {field:'IGEN_NOGETINT',headerName:'IGEN_NOGETINT',width: 150,editable: true,},
  {field:'IGEN_NOGETTAX',headerName:'IGEN_NOGETTAX',width: 150,editable: true,},
  {field:'IGEN_NOPAYTAX',headerName:'IGEN_NOPAYTAX',width: 150,editable: true,},
  {field:'IGEN_NOPAY_RSDTAX'	,headerName:'IGEN_NOPAY_RSDTAX',width: 150,editable: true,},
  {field:'IGEN_PASSINT',headerName:'IGEN_PASSINT',width: 150,editable: true,},
  {field:'IGEN_PASSTAX',headerName:'IGEN_PASSTAX',width: 150,editable: true,},
  {field:'IGEN_PASS_RSDTAX',headerName:'IGEN_PASS_RSDTAX',width: 150,editable: true,},
  {field:'IGEN_PREPAYTAX',headerName:'IGEN_PREPAYTAX',width: 150,editable: true,},
  {field:'IGEN_PREPAY_RSDTAX',headerName:'IGEN_PREPAY_RSDTAX',width: 150,editable: true,},
  {field:'IGEN_SALE_PREGETINT',headerName:'IGEN_SALE_PREGETINT',width: 150,editable: true,},
  {field:'IMC',headerName:'IMC',width: 150,editable: true,},
  {field:'IMPAIR_AMT',headerName:'IMPAIR_AMT',width: 150,editable: true,},
  {field:'IMPAIR_IAMT',headerName:'IMPAIR_IAMT',width: 150,editable: true,},
  {field:'INC_ACQAMT',headerName:'INC_ACQAMT',width: 150,editable: true,},
  {field:'INC_IACQAMT',headerName:'INC_IACQAMT',width: 150,editable: true,},
  {field:'INC_PARAMT',headerName:'INC_PARAMT',width: 150,editable: true,},
  {field:'INVEST_KIND',headerName:'INVEST_KIND',width: 150,editable: true,},
  {field:'IPARAMT_INC_NOPAYTAX',headerName:'IPARAMT_INC_NOPAYTAX',width: 150,editable: true,},
  {field:'IPARAMT_INC_NOPAY_RSDTAX',headerName:'IPARAMT_INC_NOPAY_RSDTAX',width: 150,editable: true,},
  {field:'IPARAMT_INC_PREPAYTAX',headerName:'IPARAMT_INC_PREPAYTAX',width: 150,editable: true,},
  {field:'IPARAMT_INC_PREPAY_RSDTAX',headerName:'IPARAMT_INC_PREPAY_RSDTAX',width: 150,editable: true,},
  {field:'IPREGETINT',headerName:'IPREGETINT',width: 150,editable: true,},
  {field:'IPRM_NOGETINT',headerName:'IPRM_NOGETINT',width: 150,editable: true,},
  {field:'IPRM_NOGETTAX',headerName:'IPRM_NOGETTAX',width: 150,editable: true,},
  {field:'IPRM_NOPAYTAX',headerName:'IPRM_NOPAYTAX',width: 150,editable: true,},
  {field:'IPRM_NOPAY_RSDTAX',headerName:'IPRM_NOPAY_RSDTAX',width: 150,editable: true,},
  {field:'IPRM_PASSINT',headerName:'IPRM_PASSINT',width: 150,editable: true,},
  {field:'IPRM_PASSTAX',headerName:'IPRM_PASSTAX',width: 150,editable: true,},
  {field:'IPRM_PASS_RSDTAX',headerName:'IPRM_PASS_RSDTAX',width: 150,editable: true,},
  {field:'IPRM_PREPAYTAX',headerName:'IPRM_PREPAYTAX',width: 150,editable: true,},
  {field:'IPRM_PREPAY_RSDTAX',headerName:'IPRM_PREPAY_RSDTAX',width: 150,editable: true,},
  {field:'IPRM_SALE_PREGETINT',headerName:'IPRM_SALE_PREGETINT',width: 150,editable: true,},
  {field:'IREDEMPL',headerName:'IREDEMPL',width: 150,editable: true,},
  {field:'ISALE_PREGETINT',headerName:'ISALE_PREGETINT',width: 150,editable: true,},
  {field:'ITEM',headerName:'ITEM',width: 150,editable: true,},
  {field:'JOB_STATUS',headerName:'JOB_STATUS',width: 150,editable: true,},
  {field:'LEND_QTY',headerName:'LEND_QTY',width: 150,editable: true,},
  {field:'MGN_SECU_QTY',headerName:'MGN_SECU_QTY',width: 150,editable: true,},
  {field:'MKTRATE',headerName:'MKTRATE',width: 150,editable: true,},
  {field:'MORT_QTY',headerName:'MORT_QTY',width: 150,editable: true,},
  {field:'MTY_TRADE_YMD',headerName:'MTY_TRADE_YMD',width: 150,editable: true,},
  {field:'NOGETINT_CVTPL',headerName:'NOGETINT_CVTPL',width: 150,editable: true,},
  {field:'NOT_INCLD_DIS_PASSINT',headerName:'NOT_INCLD_DIS_PASSINT',width: 150,editable: true,},
  {field:'NOT_INCLD_GEN_PASSINT',headerName:'NOT_INCLD_GEN_PASSINT',width: 150,editable: true,},
  {field:'NOT_INCLD_IDIS_PASSINT',headerName:'NOT_INCLD_IDIS_PASSINT',width: 150,editable: true,},
  {field:'NOT_INCLD_IGEN_PASSINT',headerName:'NOT_INCLD_IGEN_PASSINT',width: 150,editable: true,},
  {field:'NOT_INCLD_IPRM_PASSINT',headerName:'NOT_INCLD_IPRM_PASSINT',width: 150,editable: true,},
  {field:'NOT_INCLD_PRM_PASSINT',headerName:'NOT_INCLD_PRM_PASSINT',width: 150,editable: true,},
  {field:'NOT_SALE_IPASSINT',headerName:'NOT_SALE_IPASSINT',width: 150,editable: true,},
  {field:'NOT_SALE_PASSINT',headerName:'NOT_SALE_PASSINT',width: 150,editable: true,},
  {field:'NOT_SALE_SAV_INOGETINT',headerName:'NOT_SALE_SAV_INOGETINT',width: 150,editable: true,},
  {field:'NOT_SALE_SAV_NOGETINT',headerName:'NOT_SALE_SAV_NOGETINT',width: 150,editable: true,},
  {field:'PARAMT',headerName:'PARAMT',width: 150,editable: true,},
  {field:'PARAMT_INC_NOPAYTAX',headerName:'PARAMT_INC_NOPAYTAX',width: 150,editable: true,},
  {field:'PARAMT_INC_NOPAY_RSDTAX',headerName:'PARAMT_INC_NOPAY_RSDTAX',width: 150,editable: true,},
  {field:'PARAMT_INC_PREPAYTAX',headerName:'PARAMT_INC_PREPAYTAX',width: 150,editable: true,},
  {field:'PARAMT_INC_PREPAY_RSDTAX',headerName:'PARAMT_INC_PREPAY_RSDTAX',width: 150,editable: true,},
  {field:'PASSINT_CVTPL',headerName:'PASSINT_CVTPL',width: 150,editable: true,},
  {field:'PASSINT_INCLD_YN',headerName:'PASSINT_INCLD_YN',width: 150,editable: true,},
  {field:'PERIOD_TYCD',headerName:'PERIOD_TYCD',width: 150,editable: true,},
  {field:'PLEDGE_QTY',headerName:'PLEDGE_QTY',width: 150,editable: true,},
  {field:'PREGETINT',headerName:'PREGETINT',width: 150,editable: true,},
  {field:'PRESALE_GEN_NOGETINT',headerName:'PRESALE_GEN_NOGETINT',width: 150,editable: true,},
  {field:'PRESALE_GEN_NOGETTAX',headerName:'PRESALE_GEN_NOGETTAX',width: 150,editable: true,},
  {field:'PRESALE_IGEN_NOGETINT',headerName:'PRESALE_IGEN_NOGETINT',width: 150,editable: true,},
  {field:'PRESALE_IGEN_NOGETTAX',headerName:'PRESALE_IGEN_NOGETTAX',width: 150,editable: true,},
  {field:'PRM_NOGETINT',headerName:'PRM_NOGETINT',width: 150,editable: true,},
  {field:'PRM_NOGETTAX',headerName:'PRM_NOGETTAX',width: 150,editable: true,},
  {field:'PRM_NOPAYTAX',headerName:'PRM_NOPAYTAX',width: 150,editable: true,},
  {field:'PRM_NOPAY_RSDTAX',headerName:'PRM_NOPAY_RSDTAX',width: 150,editable: true,},
  {field:'PRM_PASSINT',headerName:'PRM_PASSINT',width: 150,editable: true,},
  {field:'PRM_PASSTAX',headerName:'PRM_PASSTAX',width: 150,editable: true,},
  {field:'PRM_PASS_RSDTAX',headerName:'PRM_PASS_RSDTAX',width: 150,editable: true,},
  {field:'PRM_PREPAYTAX',headerName:'PRM_PREPAYTAX',width: 150,editable: true,},
  {field:'PRM_PREPAY_RSDTAX',headerName:'PRM_PREPAY_RSDTAX',width: 150,editable: true,},
  {field:'PRM_SALE_PREGETINT',headerName:'PRM_SALE_PREGETINT',width: 150,editable: true,},
  {field:'REDEMPL',headerName:'REDEMPL',width: 150,editable: true,},
  {field:'REM_IPREGETINT',headerName:'REM_IPREGETINT',width: 150,editable: true,},
  {field:'REM_PREGETINT',headerName:'REM_PREGETINT',width: 150,editable: true,},
  {field:'REM_PREGETINT_CVTPL',headerName:'REM_PREGETINT_CVTPL',width: 150,editable: true,},
  {field:'SALE_PREGETINT',headerName:'SALE_PREGETINT',width: 150,editable: true,},
  {field:'SAV_DIS_NOGETINT',headerName:'SAV_DIS_NOGETINT',width: 150,editable: true,},
  {field:'SAV_DIS_NOGETINT_CVTPL',headerName:'SAV_DIS_NOGETINT_CVTPL',width: 150,editable: true,},
  {field:'SAV_DIS_NOGETTAX',headerName:'SAV_DIS_NOGETTAX',width: 150,editable: true,},
  {field:'SAV_DIS_PASSINT_CVTPL',headerName:'SAV_DIS_PASSINT_CVTPL',width: 150,editable: true,},
  {field:'SAV_ESTPL',headerName:'SAV_ESTPL',width: 150,editable: true,},
  {field:'SAV_ESTPL_BS',headerName:'SAV_ESTPL_BS',width: 150,editable: true,},
  {field:'SAV_ESTPL_IS',headerName:'SAV_ESTPL_IS',width: 150,editable: true,},
  {field:'SAV_ETC_CVTPL',headerName:'SAV_ETC_CVTPL',width: 150,editable: true,},
  {field:'SAV_GEN_CVTPL',headerName:'SAV_GEN_CVTPL',width: 150,editable: true,},
  {field:'SAV_GEN_NOGETINT',headerName:'SAV_GEN_NOGETINT',width: 150,editable: true,},
  {field:'SAV_GEN_NOGETINT_CVTPL',headerName:'SAV_GEN_NOGETINT_CVTPL',width: 150,editable: true,},
  {field:'SAV_GEN_NOGETTAX',headerName:'SAV_GEN_NOGETTAX',width: 150,editable: true,},
  {field:'SAV_GEN_PASSINT_CVTPL',headerName:'SAV_GEN_PASSINT_CVTPL',width: 150,editable: true,},
  {field:'SAV_IDIS_NOGETINT',headerName:'SAV_IDIS_NOGETINT',width: 150,editable: true,},
  {field:'SAV_IDIS_NOGETTAX',headerName:'SAV_IDIS_NOGETTAX',width: 150,editable: true,},
  {field:'SAV_IESTPL',headerName:'SAV_IESTPL',width: 150,editable: true,},
  {field:'SAV_IESTPL_BS',headerName:'SAV_IESTPL_BS',width: 150,editable: true,},
  {field:'SAV_IESTPL_IS',headerName:'SAV_IESTPL_IS',width: 150,editable: true,},
  {field:'SAV_IGEN_NOGETINT',headerName:'SAV_IGEN_NOGETINT',width: 150,editable: true,},
  {field:'SAV_IGEN_NOGETTAX',headerName:'SAV_IGEN_NOGETTAX',width: 150,editable: true,},
  {field:'SAV_IPRM_NOGETINT',headerName:'SAV_IPRM_NOGETINT',width: 150,editable: true,},
  {field:'SAV_IPRM_NOGETTAX',headerName:'SAV_IPRM_NOGETTAX',width: 150,editable: true,},
  {field:'SAV_IREDEMPL',headerName:'SAV_IREDEMPL',width: 150,editable: true,},
  {field:'SAV_PRESALE_GEN_NOGETINT',headerName:'SAV_PRESALE_GEN_NOGETINT',width: 150,editable: true,},
  {field:'SAV_PRESALE_GEN_NOGETTAX',headerName:'SAV_PRESALE_GEN_NOGETTAX',width: 150,editable: true,},
  {field:'SAV_PRESALE_IGEN_NOGETINT',headerName:'SAV_PRESALE_IGEN_NOGETINT',width: 150,editable: true,},
  {field:'SAV_PRESALE_IGEN_NOGETTAX',headerName:'SAV_PRESALE_IGEN_NOGETTAX',width: 150,editable: true,},
  {field:'SAV_PRM_NOGETINT',headerName:'SAV_PRM_NOGETINT',width: 150,editable: true,},
  {field:'SAV_PRM_NOGETINT_CVTPL',headerName:'SAV_PRM_NOGETINT_CVTPL',width: 150,editable: true,},
  {field:'SAV_PRM_NOGETTAX',headerName:'SAV_PRM_NOGETTAX',width: 150,editable: true,},
  {field:'SAV_PRM_PASSINT_CVTPL',headerName:'SAV_PRM_PASSINT_CVTPL',width: 150,editable: true,},
  {field:'SAV_REDEMPL',headerName:'SAV_REDEMPL',width: 150,editable: true,},
  {field:'SAV_REM_PREGETINT_CVTPL',headerName:'SAV_REM_PREGETINT_CVTPL',width: 150,editable: true,},
  {field:'SETTLE_YMD',headerName:'SETTLE_YMD',width: 150,editable: true,},
  {field:'STG_DET_GROUP',headerName:'STG_DET_GROUP',width: 150,editable: true,},
  {field:'STG_TYCD',headerName:'STG_TYCD',width: 150,editable: true,},
  {field:'TOT_IPREGETINT',headerName:'TOT_IPREGETINT',width: 150,editable: true,},
  {field:'TOT_PREGETINT',headerName:'TOT_PREGETINT',width: 150,editable: true,},
  {field:'TRENCH_CD',headerName:'TRENCH_CD',width: 150,editable: true,},
  {field:'WKYMD',headerName:'WKYMD',width: 150,editable: true,},
];


export default function StarredPage() {
  const [list, setList] = useState([]);
  useEffect(()=>{
    console.log(list)
  },[list])
  useEffect(()=>{
    getdata()
  },[])
  const getdata = async () => {
    try {
      const response = await axios.get("/api/list100.php");
      setList(response.data)
    } catch (error) {
      alert('조회 에러');
    }
  }
  return (
    <Box sx={{ display: 'flex' }}>
      <div>
        <Grid container rowSpacing={3} columnSpacing={3}>
            <DataGrid  sx={{ width: '1000px', height:'600px' }}
              rows={list}
              columns={columns}
              initialState={{
                pagination: {
                  paginationModel: {
                    pageSize: 10,
                  },
                },
              }}
              pageSizeOptions={[5]}
              checkboxSelection
              disableRowSelectionOnClick
            />
        </Grid>
      </div>
    </Box>
  );
}
